timeout = 5000

[headers]
Authorization = "Bearer"

[[tests]]
[tests.request]
method = "GET"
url = "https://jsonplaceholder.typicode.com/posts"
timeout = 10000
[tests.request.headers]
Request-Id = "ba4bf226-d95a-4f07-a38e-fd15470130c5"
[tests.request.queryparams]
offset = "0"
limit = "10"

[tests.response]
status = 200
body = '''
[
{
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
},
{
  "title": "qui est esse",
  "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
}
]
'''

[[tests]]
  [tests.request]
  method = "POST"
  url = "https://jsonplaceholder.typicode.com/posts"
  body = '''
  {
    "fullName": "Ivan Ivanov",
    "email": "test@test.com"
  }
  '''
  [tests.request.headers]
  Request-Id = "ba4bf226-d95a-4f07-a38e-fd15470130c5"
  

  [tests.response]
  status = 201
  body = '''
  {
    "fullName": "Ivan Ivanov",
    "email": "test@test.com"
  }
  '''
